# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.11.3               # https://pyreadiness.org/3.9/ 
  - pip=23.0.1                  # https://pip.pypa.io/en/stable/news/
  - nodejs=16.14.2
  - pip:
      # Define pip packages here -> https://pypi.org/
      - robotframework-browser==13.3.0
      - rpaframework==23.0.0    # https://rpaframework.org/releasenotes.html

rccPostInstall:
  - rfbrowser init